# 应用服务 WEB 访问端口
server:
  port: 8090
  servlet:
    context-path: /v1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.163.128:3306/wiki_base
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

wiki_back:
  project_name: wiki_back
  project_version: 1.0.0
  base_patterns: wiki1234567890

